
var tipuesearch = {"pages": [
     {"title": "ANT100 Course Website", "text": "The teaching staff is excited to share with you the adventure of anthropology, the comprehensive, varied, and integrative study of what it means to be the social animal known as Homo sapiens.", "tags": "ANT100, welcome, Bali, masks, lecture, essay, evaluation, textbook, readings, lecturer, email, office, website, location", "url": "http://anthropology.utoronto.ca/ant100"},
     {"title": "Lectures and Readings", "text": "The following lists the readings you are responsible to cover before each lecture. This readling list will be available well before lecture. After the lecture, lecturers will post lecture notes that are accompanied by study questions.", "tags": "lectures, readings, schedule", "url": "http://anthropology.utoronto.ca/ant100/lectures.html"},
     {"title": "Lecture Notes & Study Questions", "text": "Lecture notes will be made available within 72 hours after each lecture. These study questions have been carefully designed to prompt deeper thinking about the main themes within each lecture. It is highly recommended that you use these as a guide when preparing for the exams.", "tags": "lecture, notes, lectures, study, questions", "url": "http://anthropology.utoronto.ca/ant100/lecturenotes.html"},
     {"title": "The ANT100 Essay Assignment", "text": "The essay assignment is comprised of three parts due over the course of the year. Each part marks a milestone in the process of writing a formal academic research paper. You will choose a specific anthropological topic to research and think about in depth, and to report your findings. Our requirements and instructions are meant to improve your academic writing skills. There is a lot of information on this web site that explains how to write a well thought out and well referenced essay, including the due dates for the three milstone assignments. Take time to read it all!", "tags": "essay, assignment, assignments, due, date, draft, proposal, topic, deliverables", "url": "http://anthropology.utoronto.ca/ant100/essay.html"},
     {"title": "Essay Topics List", "text": "Pick any one of the following three essay topics for your assignment: Social-Cultural/Linguistic Topic (SCL), Archaeology Topic (ARC), Evolutionary Topic (EVO), The readings provided below are required readings for this assignment. You must use at least one of the scholarly readings provided with each topic for your essay.", "tags": "essay, assignment, proposal, topic, topics, SCL, ARC, EVO, reading, articles, sources", "url": "http://anthropology.utoronto.ca/ant100/essay.html"},
     {"title": "Research & Documentation", "text": 'Think of academic research as a conversation. On any topic you wish to work on (trust us, ANY!) there is a relevant conversation going on in the "literature," that is, in the printed or posted pages of refereed publications. We refer to these as your "sources." With your essay, you enter this conversation. You add your voice to those who wrote the sources. The Phase One exercise allows you to choose and evaluate your sources carefully, and to begin understanding your position on your topic as it relates to theirs. This is an extremely important part of the essay writing process - perhaps the most important.', "tags": "essay, assignment, reading, articles, sources, refereed, reference, documentation, research, peer-reviewed, list", "url": "http://anthropology.utoronto.ca/ant100/research.html"},
     {"title": "Plagiarism", "text": 'Stealing written work, in parts or as a whole, from somebody else instead of struggling to formulate your own ideas prevents you from exploring ideas for yourself or learning the skills of critical thinking and reading offered by this course. Fighting plagiarism protects students who do their own work from unfair competition.', "tags": "plagiarism, disguised coping, policy, essay, assignment, academic misconduct, academic handbook", "url": "http://anthropology.utoronto.ca/ant100/plagiarism.html"},
     {"title": "Writing Aid", "text": 'The University provides a dedicated writing aid website with many resources. You can use the dropdown index or the search function on the website to find files relevant to your course.', "tags": " essay, assignment, help, writing, aid, ELL, English Language Learning, centre, plus, workshop, workshops, ewriting", "url": "http://anthropology.utoronto.ca/ant100/writing.html"},
     {"title": "Tutorials", "text": 'Tutorials are the small-group learning experience that complements the lectures. Here you will discuss the lectures, engage in illustrative activities, and receive guidance on your essays. Tutorials are compulsory!', "tags": "tutorials, tutorial, schedule, location, deadline, sign up, TA", "url": "http://anthropology.utoronto.ca/ant100/tutorials.html"},
     {"title": "Tutorial Schedule", "text": 'If you look on Blackboard (where you signed up for a tutorial), you will see that your tutorial has a letter and a number, such as A1 or G2. To understand the table below, ignore the letter. The number of your tutorial tells you if you are one of the 1\'s or one of the 2\'s.', "tags": "tutorials, tutorial, schedule, topics, location, TA", "url": "http://anthropology.utoronto.ca/ant100/tutorialschedule.html"},
     {"title": "Evaluation & Extensions", "text": 'Your final grade will be based upon: 30% Midterm Exam (Multiple Choice) covering the first half of the course. 30% Final Exam (Multiple Choice) covering the second half of the course. 28% Essay Assignment, consisting of three deliverables due throughout the year: Topic Proposal (10%) Advanced Draft of Essay (No Mark)* Essay Revision (18%) 12% Participation in Tutorials', "tags": "evaluation, policy, marking, marks, test, exam, late, penalty, extension, illness, death", "url": "http://anthropology.utoronto.ca/ant100/evaluation.html"},
     {"title": "Contact Us", "text": 'Our method of out-of-class communication is by email or through office hours.This is very important: Please contact your TA in the first instance, before bringing any questions or issues to any other member of the course staff.', "tags": "contact, policy, lecturer, discuss, email, office", "url": "http://anthropology.utoronto.ca/ant100/contact.html"},
     {"title": "TA List", "text": 'Your TA is your first point of contact for all issues in the course. In the table, you can see who teaches what tutorial when. Scroll down to find the name and contact information of your TA.', "tags": "contact, policy, ta, teaching, assistant, email, help", "url": "http://anthropology.utoronto.ca/ant100/contact.html"},
]};



